# Your github username.
gh_username: ''
# Your full name (for use with github).
gh_name: ''
# Your github email address.
gh_email: ''
# The name of the SSH key you use with github.
gh_keyname: 'id_rsa'

# Amount of RAM for the VM.
vagrant_memory: "8096"
# Number of CPUs for the VM.
vagrant_cpus: "3"

